### ISSUE TITLE
Questions about the future of parity

### ISSUE THREAD

**Issue by gaia** [Parity-JS/dapp-wallet#1]
https://github.com/paritytech/parity/issues/7719#issuecomment-361219903 mentions that

_Parity 1.10 will not come with a built-in wallet anymore_: does this mean that we will have to use this plugin/dapp for wallet functionality?

_and versions after 1.11 and beyond will start shipping with a very minimal light-compatible wallet_: does this mean that basic wallet will not need this plugin/dapp?

Going further, can this basic wallet be used as a private node, to send tokens/ETH, specify gas/gwei and set the number of peers?

**Comment by amaurymartiny** [comment]
Hi @gaia, sorry for the late reply.

We just released Parity 1.10, and with it we deprecated the browser UI (which you could access via 127.0.0.1:8180). Instead, we now have a standalone Parity UI app, which you can read more about [here](https://wiki.parity.io/Parity-Wallet). Inside Parity UI is a dapp called `Parity Wallet`, which has the same functionalities as the built-in wallet in previous versions.

For 1.11 the plan is indeed to release a light wallet. This light wallet will be completely independent from Parity UI. It will be bundled with a light node, and we'll add basic functionalities: send/receive ether, send/receive tokens... It is meant to be lightweight and user-friendly.
